### ISSUE TITLE
ICARTT formatting error when using cleanup

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#529]
When I read in an ICARTT file and then try and run obj.clean.cleanup() to get it to CF standards, it throws the following error.  We should look at making the object compliant with what's needed for this cleanup.

```
Traceback (most recent call last):
  File "/Users/atheisen/opt/anaconda3/lib/python3.8/site-packages/xarray/core/dataset.py", line 1395, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'flag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "plot_icartt.py", line 22, in <module>
    ds.clean.cleanup()
  File "/Users/atheisen/Code/ACT/act/qc/clean.py", line 151, in cleanup
    self._obj.clean.link_variables()
  File "/Users/atheisen/Code/ACT/act/qc/clean.py", line 583, in link_variables
    self._obj[variable].attrs['ancillary_variables'] = copy.copy(ancillary_variables)
  File "/Users/atheisen/opt/anaconda3/lib/python3.8/site-packages/xarray/core/dataset.py", line 1499, in __getitem__
    return self._construct_dataarray(key)
  File "/Users/atheisen/opt/anaconda3/lib/python3.8/site-packages/xarray/core/dataset.py", line 1397, in _construct_dataarray
    _, name, variable = _get_virtual_variable(
  File "/Users/atheisen/opt/anaconda3/lib/python3.8/site-packages/xarray/core/dataset.py", line 170, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'flag'
```

**Comment by kenkehoe** [comment]
Can you provide an example dataset?

**Comment by AdamTheisen** [comment]
@kenkehoe  I was just using the sample_file in the test area (EXAMPLE_AAF_ICARTT) but now I just tried this and it's saying that the object does not have a an attribute "clean" so I think something got a little off with recent updates here.
